### ISSUE TITLE
Bearbeiten der Etagen funktioniert nicht zufriedenstellend

### ISSUE THREAD

**Issue by tloehr** [tloehr/Offene-Pflege.de#29]
Die Etagenbezeichnung lässt sich zwar anpassen, aber die Etage – egal, ob diese dann angepasst wird, ändert sich nicht dauerhaft. Bsp. Standardmässig ist das Erdgeschoss vorhanden (Bezeichnung „Erdgeschoss“), die Etage wird jedoch als „2. Untergeschoss“ angegeben. Wird dies auf „Erdgeschoss“ eingestellt, ändert sich dies nach dem aktualisieren wieder auf „2. Untergeschoss“.

**Comment by MStueble** [comment]
Lieber Torsten
Ich habe Dir eine Datei angehängt, woraus hoffentlich ersichtlich wird, was ich meinte...

![etagen-umbenennung](https://cloud.githubusercontent.com/assets/15231991/10646670/a864431c-7834-11e5-9906-7e25df52551c.jpg)

**Comment by MStueble** [comment]
Lieber Torsten
Ich muss zu obigem ergänzen: Nach dem Aktualisieren der Ansicht ist das "Ergeschoss" noch drin, doch wenn man den Menupunkt verlässt und später diesen wieder anwählt, erscheint wieder das "2. Untergeschoss".
LG
Mathias

**Comment by tloehr** [comment]
Ah. Gut beobachtet. Hab den Fehler gefunden und behoben. Zeile 314, PnlBeanEditor. :-)

**Comment by tloehr** [comment]
fixed since 1.13.1.449
