### ISSUE TITLE
Neuninstallation mit leerer Med-Datenbank akzeptiert keine Medis

### ISSUE THREAD

**Issue by tloehr** [tloehr/Offene-Pflege.de#33]
Das hat Mathias in [diesem Post](http://www.offene-pflege.de/de/component/kunena/allgemeine-diskussion/20-testphase-und-erste-rueckmeldungen-betaversion-v1-13-1#50) gut beschrieben.

**Comment by tloehr** [comment]
Das Problem war, dass die Inhalte der Tabelle **dosageform** immer vorhanden sein müssen, ob man die Med-Datenbank haben möchte oder nicht.

Ich hatte diese Tabelle aber falsch einsortiert. Ist sie leer, kommt es zu dem beschrieben NPE (Nullpointer Exception).

**Comment by tloehr** [comment]
Wird in der nächsten BETA release behoben sein.

**Comment by tloehr** [comment]
Bis dahin kann man sich damit behelfen, folgenden SQL auszuführen.
`<INSERT INTO `dosageform` VALUES (1,'','Tabletten',1,1,140,0,0,1,3),(2,'','Filmtabletten',1,1,140,0,0,1,3),(3,'','Kapseln',1,1,140,0,0,1,3),(4,'','Brausetabletten',1,1,164,0,0,0,3),(5,'','Dragees',1,1,140,0,0,1,3),(6,'','Zäpfchen, anal',1,1,145,0,0,0,0),(7,'','Zäpfchen, vaginal',1,1,145,0,0,0,0),(8,'Sirup','',2,2,144,1,0,0,3),(9,'Lösung','',2,2,144,1,0,0,3),(10,'Lösung','Tropfen',1,2,144,1,1,0,3),(11,'Lösung','Inj.s.c., Einzelampullen',1,1,147,2,0,0,0),(12,'Lösung','Inj.i.m., Einzelampullen',1,1,150,2,0,0,3),(13,'Lösung','Inj.i.v., Einzelampullen',1,1,151,2,0,0,0),(14,'Lösung','Augentropfen',1,2,281,1,1,0,0),(15,'Salbe','x',1,5,146,0,2,2,3),(16,'Suspension, Inj.s.c., Einweg-Pen','I.E.',1,2,147,2,1,0,0),(17,'Creme','x',1,5,146,0,2,2,0),(18,'','Tabletten, retard',1,1,140,0,0,3,3),(19,'','Rectal Tube',1,1,154,0,0,0,0),(20,'','Klistier, mini',1,1,155,0,0,0,0),(21,'','Lutschtabletten',1,1,140,0,0,0,0),(22,'Lösung, Inj.s.c., Einweg-Pen','I.E.',1,2,147,2,1,0,0),(23,'','Tabletten, magensaftresistent',1,1,140,0,0,3,3),(24,'','Tabletten, Schmelztabletten',1,1,140,0,0,0,3),(25,'Suspension','',2,2,144,1,1,0,3),(26,'','Tabletten, Kautabletten',1,1,140,0,0,0,0),(27,'Suspension','Beutel',1,1,144,0,0,0,0),(28,'Badezusatz','Beutel',1,1,157,0,0,0,0),(29,'Suspension, Inj.s.c., Zylinderampullen','I.E.',1,2,147,2,1,0,3),(30,'Lösung, äußerlich','x',1,2,99,0,2,0,0),(31,'','Kapseln, retard',1,1,140,0,0,3,3),(32,'','Kapseln, magensaftresistent',1,1,140,0,0,3,0),(33,'Gel','x',1,5,146,0,2,2,0),(34,'Lösung','Inf.s.c.',1,1,158,0,0,0,0),(35,'','Kapseln, Hartkapseln',1,1,140,0,0,1,3),(36,'Pulver','Beutel',1,1,161,0,0,0,3),(37,'','Pflaster, transdermal',1,1,162,0,0,0,3),(38,'','Klistier, einmal',1,1,155,0,0,0,0),(39,'Lösung','Hübe, Spray zur Inhalation',1,2,165,0,1,0,0),(40,'Lösung','Hübe, Dosieraerosol',1,2,167,0,1,0,0),(41,'Suspension','Inj.i.m., Fertigspritze',1,1,150,2,0,0,0),(42,'Lösung','Inj.s.c., Fertigspritze',1,1,147,2,0,0,0),(43,'Salbe, Augensalbe','x',1,5,170,0,2,0,0),(44,'Hydrogel, Anwendung in Wunden','x',1,5,171,0,2,0,0),(45,'Hübe, Stück','Hübe, Spray zur Inhalation',1,1,165,0,0,0,0),(46,'Hübe, Stück','Hübe, Pulver zur Inhalation',1,1,167,0,0,0,0),(47,'Lösung','Anwendungen, Faltenbalgflasche',1,1,142,0,0,0,0),(48,'','Hartkapseln, magensaftresistent',1,1,140,0,0,3,3),(49,'','Hartkapseln, retardiert',1,1,140,0,0,3,3),(50,'Paste','x',1,5,146,0,2,2,0),(51,'','Vaginaltabletten',1,1,291,0,0,0,0),(52,'Lösung','Lösung Inj.sc., Zylinderampullen I.E.',1,2,147,1,1,0,2),(53,'Tinktur (in Gramm)','Tropfen',1,5,144,0,1,0,1);<`

**Comment by tloehr** [comment]
@mstueble

**Comment by MStueble** [comment]
Hallo Torsten
Ich habe die OPDE-Version 1.13.1.439 samt DB deinstalliert und die "alte" Version von OPDE nochmals neu installiert. Das Upgrad auf 1.13.1.439 funktionierte ohne Probleme (-muss beim 1. Upgradeversuch was falsch gemacht haben) und dann - die Medikamentendatenbank war ja vorhanden - konnte ich neue Medikamente erfassen - auch mit CH-PZN. Was aber nicht funktionierte war das Zugreifen auf die Medikamente in der DB auf der Verordnungsseite der BewohnerInnen. Dort erscheint nur "keine Auswahl" (s. Bild).
Die Medikamentenliste ist jedoch in der Rubrik "Medikamentenverwaltung" vorhanden und lässt sich dort auch bearbeiten.
Herzlichst
Mathias

PS: Das mit dem SQL-Befehl habe ich nicht probiert, weil ich ja mittlerweile mit der Upgrade-Version arbeite.

![verordnungsseite](https://cloud.githubusercontent.com/assets/15231991/10732637/43fe051e-7bfb-11e5-9bc1-1e18b6bfdec8.jpg)

![verordnungen ohne auswahlmoglichkeit](https://cloud.githubusercontent.com/assets/15231991/10732869/7413d944-7bfc-11e5-9da2-6550c08cff53.jpg)

**Comment by tloehr** [comment]
Das müsste ich mir mal selbst angucken. Wenn Du möchtest dann schau ich mir das per Teamviewer an.

**Comment by MStueble** [comment]
Hallo Torsten
Einer Idee folgend habe ich den Computer wieder auf die Sprache Deutsch-Deutsch als Standard-Sprache umgestellt und siehe - ich kann nun bei den Verordnungen - ich arbeite wieder mit dem migrierten Programm (von 1.12 - auf 1.13.1.439 upgedatet) - wieder auf die Datenbank der bereits vorhandenen Medikamente zugreifen, wobei jedoch beim Eintragen des 1. Buchstabens in der "Lupen"-Maske der Warnhinweis erscheint, dass die PZN-Nr. falsch sei (PZN-Standard Deutschland). Dann folgt jedoch bei "Auswahl" die Medikamentenliste.
Irgendwie scheint also das Problem ein "Regionales" zu sein.
Als Versuch habe ich wieder auf die Sprache Deutsch-Schweiz gewechselt, Deutsch-Deutsch aus dem Windows "entfernt" und dann OPDE 1.13.1.439 neu installiert. Nun kann wieder nicht mehr auf die Medikamentendatenbank zugegriffen werden. Dies bestärkt meinen Eindruck, dass das nicht auf die Medikanentedatenbank zugreifen können was mit der Spracheinstellung des Computers zu tun haben muss.
Was Team-Viever betrifft: Ich kenne das Programm nicht. Sähe man bei der Anwendung von diesem solche Probleme, wie oben beschrieben? Oder siehst Du einfach, was bei meinem Computer abgeht, während ich die Eingaben tätige?
Für eine Antwort danke ich im Voraus
Herzlichst
Mathias

**Comment by MStueble** [comment]
PS zu obigem: Es genügt, die Datums- und Zahleneinstellungen des Systems (Win 8.1.) auf Deutsch-Deutschland zu stellen, um mit dem Programm auf die Datentabelle der Medikamente zugreifen zu können (migririertes Programm).
Bei einer Neuinstallation von 1.13.1.439 (mit installierter Medikamenten-Datenbank) tritt mit dieser Spracheinstellung der gleiche Erfolg auf, nur dass hier dann nicht mehr auf die bei der Eingabe einer neuen BewohnerIn eingetragene Ärztin zugegriffen werden kann.

**Comment by tloehr** [comment]
Lass gut sein. Ich hab's grad gefunden. Hier ist die (korrigierte) Fehlerstelle:

https://github.com/tloehr/Offene-Pflege.de/blob/97e1b7800c4b2d068194331f7818e3c215226f70/src/entity/prescription/MedPackageTools.java#L151-L152

Hier sind die Links zu den beiden Beta Testinstallationen. Bitte probier das aus.

https://www.dropbox.com/s/ts14x8rkwzrr136/opde_win32_1_13_1_507.exe?dl=0
https://www.dropbox.com/s/2b6n8yf2957epuj/opde_win64_1_13_1_507.exe?dl=0

**Comment by MStueble** [comment]
Hallo Torsten
Habe die win64-Version von 1.13.1.507 installiert und eine neue Test-WG eingerichtet. Das mit der Medikamentenverordnung funktioniert nun einwandfrei! Super! Was aber immer noch erscheint - kann jedoch in der Praxis ignoriert werden - ist die Fehlermeldung, dass die PZN nicht stimmt (s.Bild)
![fehler-meldung medi-neuverordnung](https://cloud.githubusercontent.com/assets/15231991/11269969/3e283dbc-8ebb-11e5-92d6-8ed72c4d6198.jpg)

**Comment by MStueble** [comment]
Hallo Torsten
Habe das Medikamententool weiter getestet und festgestellt, dass das PZN (Pharmacode)-System der Schweiz so seine Tücken hat.
Konkret: Nahrungsergänzungsmittel wie z.B. Burgerstein B-Komplex (GTIN: 7640121570759) haben keine Swissmedics-Nummer, weil kein Medikament (in Deutschland hat dieses Produkt eine PZN); die Schüsslersalze von Omida (Bsp. Arsenum Jodatum D12, GTIN: 7640110383391) haben zwar eine Swissmedics-Nr., diese wird jedoch nicht im GTIN erfasst, evtl. weil von der Spezialtäten-Liste und diese erfasst den Pharmacode - was ich leider bei meinen Infos an Dich bez. Pharmacode der Schweiz noch nicht wusste - nicht mehr im GTIN.
Siehe: [pharmacode_gtin_01_01_2015.pdf](https://github.com/tloehr/Offene-Pflege.de/files/49219/pharmacode_gtin_01_01_2015.pdf)

Nun, meine Lösung dieses Problems bestand darin, in meiner virtuellen WG diese "Arznei-Mittel" als Massnahmen zu verordnen, indem ich sie als neue Massnahmen eingab. (s. Bild)
![beispiel verordnung](https://cloud.githubusercontent.com/assets/15231991/11519094/6f8bf548-9897-11e5-9588-a4cc4b69a358.jpg)
Dies funktioniert und ist, zumal solche Präparate eher selten verordnet werden, auch praktikabel.
Liebe Grüsse
Mathias

**Comment by tloehr** [comment]
Hallo Mathias,

genau das ist der Grund, warum es diese Checkbox gibt ("erscheint auf stellplan obwohl..."). Ich hatte damals nämlich das gleiche Problem mit den Nahrungsergänzungsmitteln. Daher gibt es auch die Massnahmen "Nahrungsergänzungsmittel reichen". Wir haben das so gelöst, dass wir diese Massnahme verordnen und das entsprechende Mittel in den Bemerkungstext schreiben.

Und das Häkchen natürlich. Ich mach das Ticket dann zu.
